### ISSUE TITLE
Do not start new missions if battery is below threshold

### ISSUE THREAD

**Issue by anetteu** [equinor/flotilla#1524] opened 2024-04-07 12:45 UTC
**Describe the new feature you would like to see**
New missions (other than return to home) should not be started if the battery is below a threshold.

**Describe the solution you'd like**
#1019 

There are some functionality implemented already, but the status for flotilla v0.6.10 is that a mission is started with 4% battery. Have not checked the threshold, but it should be higher than 4%.

**How will this feature affect the current Threat Model?**
Leave blank for maintainers to fill out if you are uncertain about this.

**Comment by tsundvoll** [comment] 2024-04-08 10:41
Duplicate of #1459, closing this one

**Closed by tsundvoll** 2024-04-08 10:41 UTC
Labels: feature
